package com.ais.marketbackend.seguridad.domain.service;

public enum TipoEventoAuditoria {
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    RATE_LIMIT_ALCANZADO,
    REFRESH_EXITOSO,
    REFRESH_FALLIDO,
    REFRESH_REUTILIZADO,
    LOGOUT,
    USUARIO_CREADO,
    TIENDA_ASIGNADA,
    GRUPO_ASIGNADO,
    PASSWORD_CAMBIADA,
    PASSWORD_RESTABLECIDA,
    SESIONES_REVOCADAS,
    USUARIO_DESACTIVADO,
    USUARIO_BLOQUEADO,
    USUARIO_ACTIVADO,
    PASSWORD_RESET_SOLICITADO,
    PASSWORD_RESET_EXITOSO,
    PASSWORD_RESET_FALLIDO
}
